### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by AmaxCoder** [coconutbmp/leash#4]
Did anyone of you get this issue?
<img width="922" alt="image" src="https://user-images.githubusercontent.com/78669694/188316478-160b9428-526e-4bb4-8cff-d186093ddac8.png">

**Comment by coker-svg** [comment]
maybe in the mean time you can make a new  project and copy over just enough files from the repo to get it working

**Comment by LordInfernus09** [comment]
Looks like android studio needs to be updated to 2021.2.1
